Repository aq33/tgstation, pull requests merged in 2020-08, with the labels that each got.

#312 Rózne fixy
  code/game/turfs/open/_open.dm
  code/modules/jobs/job_exp.dm
  code/modules/jobs/job_types/security_officer.dm
Labels: bug, test merge, tweak

#330 Usprawnienia do metastation by Zorian Adam
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#340 Karpio-balans
  code/modules/events/carp_migration.dm
Labels: tweak

#332 Paralize od Tasera
  code/modules/projectiles/projectile/energy/stun.dm
Labels: sugestia, tweak

#326 Overhaul dźwięków broni
  sound/weapons/gunshot.ogg
  sound/weapons/gunshot_silenced.ogg
  sound/weapons/laser.ogg
  sound/weapons/revolver357shot.ogg
  sound/weapons/revolver38shot.ogg
  sound/weapons/rifleshot.ogg
  sound/weapons/rocketlaunch.ogg
  sound/weapons/shotgunpump.ogg
  sound/weapons/shotgunshot.ogg
  sound/weapons/smgshot.ogg
  sound/weapons/taser2.ogg
Labels: dźwięk

#329 Wielki overhaul dźwięków vol. 1
  code/controllers/subsystem/fire_burning.dm
  code/game/machinery/lightswitch.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/tanks/jetpack.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  code/modules/surgery/organic_steps.dm
  sound/effects/bullet_hit.ogg
  sound/effects/circularsaw.ogg
  sound/effects/closetpull.ogg
  sound/effects/crop_harvest.ogg
  sound/effects/dispenser.ogg
  sound/effects/fire.ogg
  sound/effects/lightswitch.ogg
  sound/effects/retractor_retract.ogg
  sound/effects/scalpel_cut.ogg
  sound/effects/slice.ogg
  sound/effects/suture.ogg
  sound/machines/winerror.ogg
  sound/misc/bark.ogg
  sound/misc/burp.ogg
  sound/misc/choke.ogg
  sound/misc/cough.ogg
  sound/misc/cry.ogg
  sound/misc/dance.ogg
  sound/misc/gasp.ogg
  sound/misc/groan.ogg
  sound/misc/kiss.ogg
  sound/misc/meow.ogg
  sound/misc/purr.ogg
  sound/misc/sigh.ogg
  sound/misc/sneeze.ogg
  sound/misc/sniff.ogg
  sound/misc/snore.ogg
  sound/misc/splort.ogg
  sound/misc/vomit.ogg
  sound/misc/wink.ogg
  sound/misc/yawn.ogg
  sound/vehicles/jetpack.ogg
  sound/weapons/flamethrower.ogg
Labels: dźwięk

#348 Kilka drobnych bugfixów
  _maps/RandomRuins/SpaceRuins/DJstation.dmm
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/RandomRuins/SpaceRuins/bigderelict1.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/cloning_facility.dmm
  _maps/RandomRuins/SpaceRuins/clownplanet.dmm
  _maps/RandomRuins/SpaceRuins/crashedclownship.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/emptyshell.dmm
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/gondolaasteroid.dmm
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  _maps/RandomRuins/SpaceRuins/intactemptyship.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomRuins/SpaceRuins/mrow_thats_right.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomRuins/SpaceRuins/originalcontent.dmm
  _maps/RandomRuins/SpaceRuins/power_puzzle.dmm
  _maps/RandomRuins/SpaceRuins/scav_mining.dmm
  _maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/RandomRuins/SpaceRuins/vaporwave.dmm
  _maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
Labels: Merge ready, mapping, tweak

#333 Więcej możliwości dla duchów oraz więcej !!FUN!! w ksenobiologii.
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/xeno_egg_delivery.dm
  code/game/objects/effects/spawners/xenospawner.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/cockroach.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/snake.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Merge ready, feature, test merge

#346 Możliwość otwierania niezaboltowanych drzwi hydraulic clampami
  code/game/machinery/doors/airlock.dm
Labels: Merge ready, feature, tweak

#352 Operacja falochron
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping

#353 Fix hygienebotów
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: tweak

#355 Nowe zestawy praw AI, nowe moduły AI
  code/datums/ai_laws.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/AI_modules.dm
  code/modules/research/designs/AI_module_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: tweak, tłumaczenie

#354 BSOD
  code/modules/mob/living/carbon/human/species_types/IPC.dm
Labels: tweak

#349 Polskie elementy gry
  _maps/RandomRooms/3x3/sk_rdm020_boxclutter6.dmm
  _maps/RandomRooms/5x3/sk_rdm054_metaclutter3.dmm
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomRuins/SpaceRuins/listeningstation.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomZLevels/Academy.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/TheBeach.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/ruin_caravan_victim.dmm
  _maps/shuttles/whiteship_delta.dmm
  _maps/shuttles/whiteship_meta.dmm
  _maps/templates/shelter_4.dmm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/vending/boozeomat.dm
  icons/obj/drinks.dmi
  sound/voice/medbot/jak_sie_pan_czuje.ogg
  sound/voice/medbot/jeszcze_pawulon.ogg
  sound/voice/medbot/malpiszon.ogg
  sound/voice/medbot/nie_mam_czasu.ogg
  sound/voice/medbot/pani_doktor.ogg
  sound/voice/medbot/pawulon_jest.ogg
  sound/voice/medbot/pawulon_leci.ogg
  sound/voice/medbot/piles.ogg
  sound/voice/medbot/wina.ogg
Labels: grafika, mapping, test merge

#347 Pierogi i lasery podejście drugie.
  code/game/objects/items/storage/boxes.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/projectiles/boxes_magazines/external/rechargable.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/food/food.dmi
  icons/obj/guns/energy.dmi
  icons/obj/storage.dmi
Labels: grafika, test merge, tweak

#360 Feedback zapisuje teraz mape
  code/controllers/subsystem/ticker.dm
Labels: tweak

#350 Więcej ambientów w kosmosie
  code/__DEFINES/sound.dm
  sound/ambience/space_odyssey.ogg
  sound/ambience/strauss.ogg
  sound/ambience/synthwave.ogg
Labels: Merge ready, dźwięk, test merge

#362 System walki zabawkowych mechów
  beestation.dme
  code/game/objects/items/toy_mechs.dm
  code/game/objects/items/toys.dm
  icons/obj/toy.dmi
Labels: feature

#390 Rework ścian by Doktor Kostek
  icons/turf/walls/reinforced_wall.dmi
  icons/turf/walls/rusty_reinforced_wall.dmi
  icons/turf/walls/rusty_wall.dmi
  icons/turf/walls/wall.dmi
Labels: grafika

#386 Fax
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/admin.dm
  code/__HELPERS/unique_ids.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/paperwork/fax.dm
  code/modules/paperwork/faxmachine.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/photocopier.dm
  icons/mob/ass.dmi
  icons/obj/library.dmi
  tgui/packages/tgui/interfaces/FaxMachine.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: feature, grafika, javascript, mapping, porting

#385 Porty różnych PRów
  beestation.dme
  code/__DEFINES/food.dm
  code/datums/components/crafting/tailoring.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/traitor/double_agents.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/sound.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/client/loadout/loadout_hat.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/food_and_drinks/food/condiment.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/language/egg.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/eggpeople.dm
  code/modules/power/supermatter/supermatter.dm
  icons/misc/language.dmi
  icons/mob/human_parts_greyscale.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  sound/items/Alah.ogg
  sound/items/alah_grib.ogg
  sound/voice/eggperson/egg_scream.ogg
Labels: feature, grafika, porting, tweak

#388 Nowe rzeczy na stacjach - bieżnie, telefon do syndykatu, shuttle construction kit i więcej
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/xenospawner.dm
  code/game/objects/structures/crates_lockers/crates/large.dm
  code/modules/antagonists/morph/morph.dm
Labels: feature, mapping, tweak

#389 Techpriest Kit
  code/game/objects/items/holy_weapons.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/surgery/organs/autosurgeon.dm
Labels: feature

#357 Rework dronów i innych rzeczy by Quartofel
  code/game/machinery/droneDispenser.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/hivebot.dmi
  icons/obj/machines/droneDispenser.dmi
Labels: feature, grafika, test merge, tweak

#325 Create ostrycienmgly
  beestation.dme
  code/__DEFINES/melee.dm
  code/datums/martial/sharpshadowofthemist.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/sharp_star.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/voidlight.dm
  code/game/objects/ostra_gwiazda.dmi
  code/modules/spells/spell_types/sharpstar.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/mimescroll.dmi
  icons/obj/ostra_gwiazda.dmi
Labels: feature, test merge

#396 Odrzucone rzeczy z bee vol. 1
  beestation.dme
  code/__DEFINES/wires.dm
  code/__HELPERS/unsorted.dm
  code/datums/components/crafting/recipes.dm
  code/datums/wires/scan_gate.dm
  code/game/machinery/computer/law.dm
  code/game/machinery/recharger.dm
  code/game/machinery/scan_gate.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/energy/_energy.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/ammunition/energy/stun.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/energy_gun.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/misc/beam_rifle.dm
  code/modules/research/designs/power_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/power.dmi
Labels: feature, grafika

#392 Metacoin shop organy
  beestation.dme
  code/modules/client/loadout/loadout_organ.dm
  code/modules/jobs/job_types/_job.dm
Labels: feature

#351 Powrót Kilo
  _maps/map_files/KiloStation/KiloStation.dmm
  code/game/objects/structures/displaycase.dm
  config/Sage/maps.txt
  config/maps.txt
  tools/convert_map_to_smartcables.py
Labels: mapping, test merge

#399 HEV suit zamiast prototype hardsuita
  code/modules/clothing/spacesuits/hardsuit.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  sound/items/hev/hev_logon.ogg
  sound/items/hev/hev_morphine.ogg
Labels: feature, grafika

#393 Kolejny balans trybów
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/events/blob.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/creep_awakening.dm
  code/modules/events/devil.dm
  code/modules/events/floorcluwne.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/nightmare.dm
  code/modules/events/pirates.dm
  code/modules/events/portal_storm.dm
  code/modules/events/space_dragon.dm
Labels: tweak

#402 Płytki "Borgi" dostępne w mechfabach
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: tweak

#373 Tłumaczenie Bloba oraz resprite
  code/modules/antagonists/blob/blob.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/blob/blobstrains/_blobstrain.dm
  code/modules/antagonists/blob/blobstrains/blazing_oil.dm
  code/modules/antagonists/blob/blobstrains/cryogenic_poison.dm
  code/modules/antagonists/blob/blobstrains/electromagnetic_web.dm
  code/modules/antagonists/blob/blobstrains/energized_jelly.dm
  code/modules/antagonists/blob/blobstrains/explosive_lattice.dm
  code/modules/antagonists/blob/blobstrains/networked_fibers.dm
  code/modules/antagonists/blob/blobstrains/pressurized_slime.dm
  code/modules/antagonists/blob/blobstrains/reactive_spines.dm
  code/modules/antagonists/blob/blobstrains/regenerative_materia.dm
  code/modules/antagonists/blob/blobstrains/replicating_foam.dm
  code/modules/antagonists/blob/blobstrains/shifting_fragments.dm
  code/modules/antagonists/blob/blobstrains/synchronous_mesh.dm
  code/modules/antagonists/blob/blobstrains/zombifying_pods.dm
  code/modules/antagonists/blob/overmind.dm
  code/modules/antagonists/blob/powers.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/antagonists/blob/structures/factory.dm
  code/modules/antagonists/blob/structures/node.dm
  code/modules/antagonists/blob/structures/resource.dm
  code/modules/antagonists/blob/structures/shield.dm
  html/antagtips/blob.html
  html/img/blobcore.png
  html/img/blobnode.png
  icons/mob/blob.dmi
Labels: grafika, tłumaczenie

#408 Tłumaczenie tipów
  strings/sillytips.txt
  strings/tips.txt
Labels: Merge ready

#414 Hotkey - zmiana wyposażenia mecha
  code/datums/keybinding/carbon.dm
Labels: tweak

#411 zamieniono attacktext na hits u zardoników grzyba
  code/modules/antagonists/blob/blob_mobs.dm
Labels: tweak
