Repository aq33/tgstation, pull requests merged in 2020-11, with the labels that each got.

#531 Nowe polecenia dla Cybersuna
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  code/game/objects/structures/ghost_role_spawners.dm
Labels: tweak

#529 Tweaki i rebalanse
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/assembly/flash.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/paperwork/contract.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/energy/ebow.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/spells/spell_types/devil.dm
Labels: test merge, tweak

#542 Tłumaczenia napisów i opisów na drogowskazach, znakach i tabliczkach
  code/game/objects/structures/signs/signs_departments.dm
  code/game/objects/structures/signs/signs_maps.dm
  code/game/objects/structures/signs/signs_warning.dm
  icons/obj/decals.dmi
  icons/obj/mining.dmi
Labels: grafika

#545 Komunikaty dźwiękowe dla wiadomości radiowych
  code/__DEFINES/preferences.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/modules/client/preferences_toggles.dm
  sound/effects/radio.ogg
Labels: dźwięk

#552 Drobne tłumaczenia
  code/_globalvars/lists/flavor_misc.dm
  icons/mob/ai.dmi
  icons/obj/doors/airlocks/external/external.dmi
  icons/obj/doors/airlocks/highsec/highsec.dmi
  icons/obj/doors/airlocks/station/command.dmi
  icons/obj/doors/airlocks/station/engineering.dmi
  icons/obj/doors/door_assembly.dmi
  icons/obj/doors/doorfire.dmi
  icons/obj/doors/doorfireglass.dmi
  icons/obj/items_and_weapons.dmi
  icons/obj/library.dmi
  icons/obj/status_display.dmi
  icons/turf/decals.dmi
Labels: grafika, tłumaczenie

#530 Zakładanie kont bankowych
  code/game/machinery/computer/card.dm
  code/modules/economy/account.dm
Labels: feature, test merge

#492 Rebalans nanitów
  code/datums/components/nanites.dm
  code/modules/research/techweb/all_nodes.dm
Labels: tweak

#555 Nowe sprajty, hakowanie i tweaki do jukeboxa
  beestation.dme
  code/__DEFINES/wires.dm
  code/controllers/subsystem/jukeboxes.dm
  code/datums/wires/jukebox.dm
  code/game/machinery/dance_machine.dm
  code/game/machinery/jukebox.dm
  code/game/sound.dm
  icons/obj/machines/jukebox.dmi
Labels: dźwięk, feature, grafika

#556 Fix ikony piły abductorów
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
Labels: tweak
