Repository aq33/tgstation, pull requests merged in 2020-09, with the labels that each got.

#367 Tłumaczenie code phrases
  strings/ion_laws.json
Labels: test merge, tłumaczenie

#374 Tłumaczenia
  code/controllers/subsystem/nightshift.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  html/antagtips/nukie.html
  html/antagtips/traitor.html
  html/antagtips/wizard.html
  html/antagtips/xeno.html
Labels: test merge, tłumaczenie

#363 Tłumaczenie ogólne
  code/datums/mutations/body.dm
  code/game/machinery/announcement_system.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/vending/assist.dm
  code/modules/vending/autodrobe.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/cigarette.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/coffee.dm
  code/modules/vending/cola.dm
  code/modules/vending/drinnerware.dm
  code/modules/vending/games.dm
  code/modules/vending/liberation_toy.dm
  code/modules/vending/magivend.dm
  code/modules/vending/medical.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/mining.dm
  code/modules/vending/modularpc.dm
  code/modules/vending/nutrimax.dm
  code/modules/vending/security.dm
  code/modules/vending/snack.dm
  code/modules/vending/sovietsoda.dm
  code/modules/vending/sustenance.dm
  code/modules/vending/toys.dm
  code/modules/vending/wardrobes.dm
Labels: test merge, tłumaczenie

#417 Fix bugów i różnych runtime
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/__DEFINES/preferences.dm
  code/game/atoms.dm
  code/game/machinery/autolathe.dm
  code/game/mecha/working/clarke.dm
  code/game/mecha/working/working.dm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/dolphin.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/slime/life.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Merge ready, bug, tweak

#338 Explorer
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  beestation.dme
  code/__DEFINES/jobs.dm
  code/datums/traits/negative.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/items/religion.dm
  code/game/objects/items/toys.dm
  code/game/objects/ostra_gwiazda.dmi
  code/modules/events/wizard/departmentrevolt.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/explorer.dm
  code/modules/jobs/jobs.dm
  config/jobs.txt
  icons/obj/explorer_voucher.dmi
  icons/obj/exploring_voucher.dmi
Labels: feature, mapping, test merge

#413 Nowy mech - Tac X1 Alpha
  beestation.dme
  code/game/mecha/combat/alpha.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/items/toy_mechs.dm
  code/modules/cargo/bounties/mech.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mecha/mech_construct.dmi
  icons/mecha/mech_construction.dmi
  icons/mecha/mecha.dmi
  icons/mob/actions/actions_mecha.dmi
  icons/obj/toy.dmi
Labels: feature, grafika, test merge

#415 Spolszczenie Abductorów
  code/modules/antagonists/abductor/abductee/abductee_objectives.dm
  code/modules/antagonists/abductor/abductor.dm
  code/modules/antagonists/abductor/equipment/abduction_gear.dm
  code/modules/antagonists/abductor/equipment/gland.dm
  code/modules/antagonists/abductor/ice_abductor.dm
  code/modules/antagonists/abductor/machinery/camera.dm
  code/modules/antagonists/abductor/machinery/console.dm
  code/modules/antagonists/abductor/machinery/dispenser.dm
  code/modules/antagonists/abductor/machinery/experiment.dm
  code/modules/antagonists/abductor/machinery/pad.dm
  html/antagtips/abductor.html
  strings/abductee_objectives.txt
Labels: tłumaczenie

#420 Kolejna porcja portów
  beestation.dme
  code/__DEFINES/anomalies.dm
  code/controllers/subsystem/research.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/modules/assembly/signaler.dm
  code/modules/cargo/exports/parts.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/suits/reactive_armour.dm
  code/modules/mob/mob.dm
  code/modules/research/anomaly/anomaly_core.dm
  code/modules/research/anomaly/explosive_compressor.dm
  code/modules/research/anomaly/raw_anomaly.dm
  code/modules/surgery/organs/organ_internal.dm
  icons/obj/assemblies/new_assemblies.dmi
  icons/obj/machines/research.dmi
Labels: feature, porting, tweak

#421 Amunicja dla mechów, garść resprite'ów i nowe piupiu
  beestation.dme
  code/game/mecha/combat/combat.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/equipment/weapons/mecha_ammo.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_defense.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/uplink/uplink_items.dm
  icons/mecha/mecha_ammo.dmi
  icons/mecha/mecha_equipment.dmi
  sound/weapons/chaingun.ogg
  sound/weapons/railgun.ogg
  sound/weapons/scattershot.ogg
Labels: dźwięk, grafika, tweak

#424 Let's go practice medicine
  code/modules/surgery/tools.dm
  code/modules/uplink/uplink_items.dm
  icons/mob/inhands/equipment/medical_lefthand.dmi
  icons/mob/inhands/equipment/medical_righthand.dmi
  icons/obj/surgery.dmi
Labels: grafika, tweak

#430 Kolejne buffy dla sec!? Taser Edition
  code/modules/projectiles/guns/energy/stun.dm
Labels: tweak

#427 Portal Gun
  code/modules/projectiles/guns/energy/special.dm
  code/modules/research/designs/weapon_designs.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
  icons/obj/stationobjs.dmi
  sound/weapons/pgunblue.ogg
  sound/weapons/pgunorangemanbad.ogg
Labels: dźwięk, grafika, tweak

#359 Losowe silniki
  _maps/RandomEngines/emergency_engine.dmm
  _maps/RandomEngines/kilo_singulo.dmm
  _maps/RandomEngines/kilo_supermatter.dmm
  _maps/RandomEngines/kilo_teg.dmm
  _maps/RandomEngines/kilo_tesla.dmm
  _maps/RandomEngines/meta_singulo.dmm
  _maps/RandomEngines/meta_supermatter.dmm
  _maps/RandomEngines/meta_teg.dmm
  _maps/RandomEngines/meta_tesla.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  beestation.dme
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/mapping.dm
  code/game/objects/effects/spawners/enginespawner.dm
  code/modules/mapping/random_engines.dm
Labels: feature, grafika, mapping, porting, test merge

#431 Feedback jest dobry jak jest
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: tweak

#432 Strój listonosza w cargo vendorze
  code/modules/vending/wardrobes.dm
Labels: feature

#401 Nowe rzeczy na kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: mapping

#437 Fix clarka
  icons/mecha/mech_construct.dmi
  icons/mecha/mech_construction.dmi
Labels: bug, tweak

#438 Nowy sprite hełmu atmos hardsuita
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: grafika

#407 Stormdrive
  _maps/RandomEngines/kilo_stormdrive.dmm
  _maps/RandomEngines/meta_stormdrive.dmm
  beestation.dme
  code/modules/cargo/exports/large_objects.dm
  code/modules/mapping/random_engines.dm
  code/modules/power/singularity/particle_accelerator/particle.dm
  code/modules/power/stormdrive/control_rods.dm
  code/modules/power/stormdrive/stormdrive.dm
  code/modules/surgery/organs/lungs.dm
  icons/effects/atmospherics.dmi
  icons/obj/computer.dmi
  icons/obj/stormdrive/control_rod.dmi
  icons/obj/stormdrive/reactor.dmi
  icons/obj/stormdrive/reactor_parts.dmi
  icons/obj/stormdrive/reactor_solgov.dmi
  sound/effects/stormdrive/core_overheating.ogg
  sound/effects/stormdrive/error.ogg
  sound/effects/stormdrive/error2.ogg
  sound/effects/stormdrive/error3.ogg
  sound/effects/stormdrive/explode.ogg
  sound/effects/stormdrive/falloutwind.ogg
  sound/effects/stormdrive/meltdown.ogg
  sound/effects/stormdrive/startup.ogg
  sound/effects/stormdrive/startup2.ogg
  tgui/.eslintrc.yml
  tgui/packages/tgui/interfaces/StormdriveConsole.js
  tgui/packages/tgui/interfaces/StormdriveControlRods.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: feature, grafika, javascript, porting

#434 Update map
  _maps/RandomRuins/SpaceRuins/DJstation.dmm
  _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
  _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/RandomRuins/SpaceRuins/asteroid2.dmm
  _maps/RandomRuins/SpaceRuins/asteroid5.dmm
  _maps/RandomRuins/SpaceRuins/bus.dmm
  _maps/RandomRuins/SpaceRuins/crashedclownship.dmm
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/gondolaasteroid.dmm
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/RandomRuins/SpaceRuins/vaporwave.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
Labels: mapping

#444 Fix randomowych silników [gotowy do test merge]
  _maps/RandomEngines/kilo_singulo.dmm
  _maps/RandomEngines/kilo_stormdrive.dmm
  _maps/RandomEngines/kilo_tesla.dmm
  tgui/packages/tgui/public/tgui.bundle.js
Labels: mapping, tweak
