Repository aq33/tgstation, pull requests merged in 2020-12, with the labels that each got.

#540 Cele załogi - tłumaczenie
  code/modules/crew_objectives/_crew_objectives.dm
  code/modules/crew_objectives/cargo_objectives.dm
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/crew_objectives/command_objectives.dm
  code/modules/crew_objectives/engineering_objectives.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/crew_objectives/science_objectives.dm
  code/modules/crew_objectives/security_objectives.dm
Labels: tłumaczenie

#560 Experimental Wrench + rebalans Uberpiły
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/surgery/tools.dm
  code/modules/uplink/uplink_items.dm
  icons/obj/tools.dmi
  sound/items/eureka_channel.ogg
  sound/items/eureka_teleport.ogg
Labels: feature, tweak

#563 Dodanie instrumentów do Kilostation
  _maps/map_files/KiloStation/KiloStation.dmm
  code/game/objects/items/devices/instruments.dm
Labels: mapping

#570 Poduszki dla samotnych
  beestation.dme
  code/game/objects/items/dakimakuras.dm
  code/modules/vending/toys.dm
  icons/mob/inhands/items_lefthand.dmi
  icons/mob/inhands/items_righthand.dmi
  icons/obj/dakis.dmi
Labels: feature, grafika

#561 Dalsze udoskonalenia oświetlenia
  beestation.dme
  code/__DEFINES/flags.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/lighting.dm
  code/_onclick/hud/plane_master.dm
  code/datums/components/overlay_lighting.dm
  code/game/atoms_movable.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/firealarm.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/plasmamen.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/mob_defines.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  icons/effects/light_overlays/light_cone.dmi
  icons/effects/lighting_object.dmi
Labels: Zielone światło, feature, porting, tweak

#562 Wincyj dźwięków
  code/game/mecha/mecha.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  sound/items/megaphonepp.ogg
  sound/mecha/mechboot.ogg
  sound/mecha/welcomebrigador.ogg
  sound/misc/gnome.ogg
  sound/voice/dialup.ogg
  sound/voice/gag.ogg
  sound/voice/human/femalechoke.ogg
  sound/voice/human/femalecough1.ogg
  sound/voice/human/femalecough2.ogg
  sound/voice/human/femaledeath1.ogg
  sound/voice/human/femaledeath2.ogg
  sound/voice/human/femalegasp1.ogg
  sound/voice/human/femalegasp2.ogg
  sound/voice/human/femalesigh1.ogg
  sound/voice/human/femalesigh2.ogg
  sound/voice/human/femalesigh3.ogg
  sound/voice/human/femalesigh4.ogg
  sound/voice/human/femalesneeze1.ogg
  sound/voice/human/femalesneeze2.ogg
  sound/voice/human/malecough1.ogg
  sound/voice/human/maledeath1.ogg
  sound/voice/human/maledeath2.ogg
  sound/voice/human/maledeath3.ogg
  sound/voice/human/maledeath4.ogg
  sound/voice/human/malesneeze1.ogg
Labels: Zielone światło, dźwięk, tweak

#568 Przywraca gender reasigment surgery
  beestation.dme
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/surgery/gender_reassignment.dm
Labels: feature

#564 ASG zamiast donksoftu
  code/game/mecha/equipment/weapons/mecha_ammo.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/projectiles/ammunition/caseless/foam.dm
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/projectile/reusable/foam_dart.dm
  code/modules/vending/toys.dm
  icons/mecha/mecha_ammo.dmi
  icons/mecha/mecha_equipment.dmi
  icons/obj/guns/toy.dmi
  icons/obj/toy.dmi
Labels: Zielone światło, feature, tweak

#577 [GOTOWE DO MERGE]Przyciski do manipulacji metacoinami w player panel
  beestation.dme
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/modify_metacoins.dm
Labels: Zielone światło, test merge, tweak

#576 [GOTOWE DO TESTMERGE]Polskie znaki w imionach postaci
  code/__HELPERS/text.dm
Labels: Zielone światło, tweak

#587 Github Actions dla CRLF dla plików z .gitattributes
  .github/workflows/line_endings_lint.yml
Labels: zewnętrzne

#559 Usprawnienia kodu
  code/__DEFINES/flags.dm
  code/controllers/subsystem/timer.dm
  code/datums/diseases/advance/symptoms/heal.dm
  code/game/machinery/fat_sucker.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/stacks/stack.dm
  code/game/turfs/open/space/space.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/individual_logging.dm
  code/modules/assembly/assembly.dm
  code/modules/client/verbs/looc.dm
  code/modules/client/verbs/ooc.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/gun.dm
  code/modules/tgchat/to_chat.dm
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/public/tgui-panel.bundle.js
Labels: gotowe do merge, tweak

#584 Immersywne oddychanie
  code/modules/mob/living/carbon/human/life.dm
  sound/effects/gasmask1.ogg
  sound/effects/gasmask10.ogg
  sound/effects/gasmask2.ogg
  sound/effects/gasmask3.ogg
  sound/effects/gasmask4.ogg
  sound/effects/gasmask5.ogg
  sound/effects/gasmask6.ogg
  sound/effects/gasmask7.ogg
  sound/effects/gasmask8.ogg
  sound/effects/gasmask9.ogg
Labels: Dźwięk, Gotowe do merge, Tweak

#567 Tweak inducera i power cell chargera
  code/game/machinery/cell_charger.dm
  code/game/objects/items/inducer.dm
Labels: Gotowe do merge, Tweak

#571 Nanity 2.0
  beestation.dme
  code/__DEFINES/melee.dm
  code/__DEFINES/nanites.dm
  code/__DEFINES/say.dm
  code/__DEFINES/traits.dm
  code/datums/components/nanites.dm
  code/datums/martial/nanojutsu.dm
  code/datums/saymode.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_misc_items.dm
  code/modules/research/nanites/nanite_misc_mobs.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/buffing.dm
  code/modules/research/nanites/nanite_programs/protocols.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
  code/modules/research/nanites/program_disks.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/nanophage.dmi
  icons/obj/items_and_weapons.dmi
  sound/misc/nanobirth.ogg
  sound/misc/nanobuzz.ogg
  sound/misc/nanodead.ogg
Labels: Feature, Gotowe do merge, Grafika, Tweak, Złote Skarpety

#575 Ambicje
  beestation.dme
  code/__DEFINES/antagonists.dm
  code/__DEFINES/~ambitions.dm
  code/__HELPERS/roundend.dm
  code/datums/mind.dm
  code/modules/admin/antag_panel.dm
  code/modules/admin/check_antagonists.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/ambitions/ambition.dm
  code/modules/ambitions/ambition_templates.dm
  code/modules/ambitions/antag_datums.dm
  code/modules/ambitions/mind.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/uplink/uplink_items.dm
Labels: Feature, Gotowe do merge, Tłumaczenie

#589 Security Pistol [GOTOWE DO MERGE]
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/antagonists/roundstart_special/undercover/undercover.dm
  code/modules/cargo/packs.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
  sound/weapons/dryfire.ogg
  sound/weapons/secshot.ogg
Labels: Dźwięk, Feature, Gotowe do merge, Grafika, Tweak

#597 Naprawa improvised shotgun
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: Tweak

#573 Więcej ambientu
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/area/areas.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/spaceheater.dm
  code/game/mecha/mech_fabricator.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/mining/machine_redemption.dm
  code/modules/power/generator.dm
  code/modules/power/smes.dm
  code/modules/research/machinery/_production.dm
  code/modules/security_levels/security_levels.dm
  sound/machines/electronics/computer_mid.ogg
  sound/machines/electronics/computer_mid1.ogg
  sound/machines/electronics/computer_mid2.ogg
  sound/machines/electronics/computer_mid3.ogg
  sound/machines/electronics/computer_mid4.ogg
  sound/machines/electronics/computer_mid5.ogg
  sound/machines/electronics/computer_start.ogg
  sound/machines/electronics/computer_stop.ogg
  sound/machines/electronics/lathe_idle.ogg
  sound/machines/electronics/lathe_start.ogg
  sound/machines/electronics/lathe_stop.ogg
  sound/machines/electronics/lathe_working.ogg
  sound/machines/electronics/lathe_working2.ogg
  sound/machines/electronics/lathe_working3.ogg
  sound/machines/electronics/lathe_working4.ogg
  sound/machines/electronics/transformator_mid.ogg
  sound/machines/electronics/transformator_start.ogg
  sound/machines/electronics/transformator_stop.ogg
  sound/machines/ormsmelt.ogg
  sound/machines/thermal/scrubber_mid1.ogg
  sound/machines/thermal/scrubber_mid2.ogg
  sound/machines/thermal/scrubber_start.ogg
  sound/machines/thermal/scrubber_stop.ogg
  sound/machines/thermal/thermal_mid.ogg
  sound/machines/thermal/vent_mid.ogg
  sound/machines/thermal/vent_start.ogg
  sound/machines/thermal/vent_stop.ogg
  sound/misc/delta_alert.ogg
  sound/misc/red_alert.ogg
Labels: Dźwięk, Gotowe do merge, Tweak
