Repository aq33/tgstation, pull requests merged in 2020-10, with the labels that each got.

#429 MINIMUM_AGE dla dronów
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
  code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
Labels: tweak

#368 Polskie tłumaczenia napisów końcowych orazpodsumowania bezpieczeństwa
  code/game/gamemodes/brother/traitor_bro.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/gangs/gangs.dm
  code/game/gamemodes/hivemind/hivemind.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/monkey/monkey.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/overthrow/overthrow.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/double_agents.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: tłumaczenie

#439 Spacepody
  _maps/RandomZLevels/spacebattle.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  beestation.dme
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/spacepods.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/spacepod.dm
  code/game/objects/items/stacks/rods.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/cable.dm
  code/modules/power/pipecleaners.dm
  code/modules/projectiles/projectile.dm
  code/modules/research/designs/spacepod_designs.dm
  code/modules/research/machinery/protolathe.dm
  code/modules/research/machinery/techfab.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/spacepods/construction.dm
  code/modules/spacepods/equipment.dm
  code/modules/spacepods/parts.dm
  code/modules/spacepods/physics.dm
  code/modules/spacepods/prebuilt.dm
  code/modules/spacepods/spacepod.dm
  goon/icons/obj/spacepods/2x2.dmi
  goon/icons/obj/spacepods/construction_2x2.dmi
  goon/icons/obj/spacepods/parts.dmi
  icons/obj/doors/1x2blast_hor.dmi
  icons/obj/doors/1x2blast_vert.dmi
  icons/obj/doors/1x3blast_hor.dmi
  icons/obj/doors/1x3blast_vert.dmi
  icons/obj/doors/1x4blast_hor.dmi
  icons/obj/doors/1x4blast_vert.dmi
  icons/obj/spacepods/2x2.dmi
  icons/obj/spacepods/parts.dmi
Labels: feature, grafika, mapping, porting, test merge

#428 Kolejne buffy dla sec: kosmobagiety
  code/modules/reagents/chemistry/machinery/pandemic.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/ears.dmi
  icons/mob/eyes.dmi
  icons/mob/head.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/card.dmi
  icons/obj/chemical.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/decals.dmi
  icons/obj/doors/airlocks/station/security.dmi
  icons/obj/pda.dmi
  icons/obj/storage.dmi
  icons/obj/vending.dmi
Labels: grafika, test merge, tweak

#448 seks na guzik, czyli jak dostać się na elfy userotha
  code/game/objects/items/granters.dm
  code/modules/spells/spell_types/godhand.dm
  code/modules/spells/spell_types/touch_attacks.dm
  code/modules/vending/wardrobes.dm
  icons/mob/actions/actions_spells.dmi
  icons/mob/actions/backgrounds.dmi
Labels: feature, sugestia, test merge

#482 Asteroida na MetaStation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: mapping

#447 Borgi, podrasowanie ubran i drobne zmiany balansu
  code/modules/cargo/packs.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/chronosuit.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/clothing/under/costume.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/ruins/spaceruin_code/forgottenship.dm
  code/modules/vending/wardrobes.dm
  icons/mob/head.dmi
  icons/mob/robots.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: feature, grafika, test merge, tweak

#468 straszne potwory
  config/game_options.txt
Labels: tweak

#480 GR-3YT1.DE Locker Exosuit
  beestation.dme
  code/datums/components/crafting/recipes.dm
  code/game/machinery/doors/airlock.dm
  code/game/mecha/working/lockermech.dm
  icons/mecha/mecha.dmi
  icons/mecha/mecha_equipment.dmi
  sound/mecha/scrapstep.ogg
Labels: feature, grafika

#479 Bluespace Pipes, czyli nowe zabawki dla Szymona
  beestation.dme
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/objects/items/RPD.dm
  code/modules/atmospherics/machinery/pipes/bluespace.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/atmospherics/pipes/bluespace.dmi
Labels: feature, porting, test merge

#483 Tryb gry teraz zależy od ogólnej liczby graczy a nie od liczby "gotowych" graczy.
  code/datums/helper_datums/getrev.dm
  code/game/gamemodes/game_mode.dm
Labels: test merge, tweak

#501 certyfikowany grenade launcher moment
  code/modules/uplink/uplink_items.dm
Labels: tweak

#484 Bugfixy 3 [Gotowe do test merge]
  code/controllers/subsystem/shuttle.dm
  code/datums/diseases/advance/advance.dm
  code/datums/mind.dm
  code/game/machinery/recharger.dm
  code/game/turfs/open/_open.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/shuttle/special.dm
Labels: test merge, tweak

#487 Replaye [Gotowe do test merge]
  beestation.dme
  code/__DEFINES/subsystems.dm
  code/_globalvars/logging.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/chat.dm
  code/controllers/subsystem/demo.dm
  code/controllers/subsystem/garbage.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/turfs/change_turf.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_investigate.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/create_poll.dm
  code/modules/admin/holder2.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/secrets.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_parser.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/admin/verbs/bluespacearty.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/fps.dm
  code/modules/admin/verbs/getlogs.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/admin/verbs/possess.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/reestablish_db_connection.dm
  code/modules/admin/verbs/spawnobjasmob.dm
  code/modules/admin/verbs/tripAI.dm
  code/modules/admin/view_variables/mass_edit_variables.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/demo/hooks.dm
  code/modules/shuttle/on_move.dm
  code/modules/tgchat/to_chat.dm
  tools/demo_condenser.js
Labels: feature, porting

#517 bugfix rubber stampów
  code/modules/paperwork/paper.dm
  tgui/packages/tgui/interfaces/PaperSheet.js
  tgui/public/tgui.bundle.js
Labels: bug, tweak

#508 fix na jednostrzałowe pulse rifle
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: tweak

#488 Update tgui 4 [merge ready]
  .vscode/settings.json
  code/datums/wires/_wires.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui_panel/external.dm
  code/modules/tgui_panel/tgui_panel.dm
  tgui/packages/tgui/interfaces/DecalPainter.js
  tgui/packages/tgui/interfaces/GravityGenerator.js
  tgui/packages/tgui/interfaces/HypnoChair.js
  tgui/packages/tgui/interfaces/Wires.js
  tgui/public/tgui.bundle.js
Labels: javascript, porting

#490 seks u diabła
  code/__DEFINES/contracts.dm
  code/game/gamemodes/devil/objectives.dm
  code/game/objects/items/granters.dm
  code/modules/antagonists/devil/sintouched/objectives.dm
  code/modules/antagonists/devil/sintouched/sintouched.dm
  code/modules/library/lib_codex_gigas.dm
  code/modules/mob/living/living.dm
  code/modules/paperwork/contract.dm
  code/modules/spells/spell_types/devil.dm
Labels: feature

#520 fix zapisywania pozycji kamery dla AI
  code/modules/mob/living/silicon/ai/ai.dm
Labels: bug, tweak

#507 Nowy atmos hardsuit autorstwa Kolegi (pipi popo #6667) - wersja bez błędów gita
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: grafika

#486 Bronie i tweaki
  code/game/objects/effects/temporary_visuals/projectiles/muzzle.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/plasma.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/energy/stun.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/projectiles.dmi
Labels: feature, grafika, test merge, tweak

#518 Genetyka 2.0
  code/__DEFINES/DNA.dm
  code/__DEFINES/traits.dm
  code/_onclick/click.dm
  code/datums/beam.dm
  code/datums/mutations/_combined.dm
  code/datums/mutations/actions.dm
  code/datums/mutations/body.dm
  code/datums/mutations/sight.dm
  code/game/objects/items/dna_injector.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  icons/mob/actions/actions_spells.dmi
  icons/obj/projectiles.dmi
Labels: feature, grafika, nagroda, porting

#509 Nowy implant dla sec generujący dźwięk metrocop death z HL2 przy śmierci
  beestation.dme
  code/game/objects/items/implants/implant_security.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  sound/misc/securitydown.ogg
Labels: dźwięk, feature, test merge

#499 Rebalans baterii eksportowych
  code/game/machinery/battery.dm
Labels: tweak
