Repository aq33/tgstation, pull requests merged in 2020-06, with the labels that each got.

#56 Kanadyjskie, włoskie i francuskie zamienniki
  strings/canadian_replacement.json
  strings/french_replacement.json
  strings/italian_replacement.json
Labels: tłumaczenie

#58 Hardcode strefy czasowej na polską
  code/game/world.dm
Labels: bug

#59 Polskie znaki na kartkach papieru
  code/modules/paperwork/paper.dm
Labels: feature

#67 Zmiana formy pull requestów na coś prostszego
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#63 Update headcrab.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
Labels: feature

#64 Update alien.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
Labels: feature

#66 Update giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: feature

#65 Update clown.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
Labels: feature

#68 Update skeleton.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
Labels: feature

#69 Update gondola.dm
  code/modules/mob/living/simple_animal/friendly/gondola.dm
Labels: feature

#62 PSK Hermaszewski - tłumaczenia
  code/__DEFINES/radio.dm
  code/datums/ai_laws.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events.dm
  code/game/gamemodes/objective.dm
  icons/obj/contraband.dmi
  icons/obj/decals.dmi
  strings/1000_most_common.txt
  strings/boomer.json
  strings/dreamstrings.txt
  strings/greek_letters.txt
  strings/locations.json
  strings/numbers_as_words.txt
  strings/phobia.json
  strings/phonetic_alphabet.txt
  strings/wanted_message.json
Labels: tłumaczenie

#79 Polskie imiona i nazwiska dla postaci
  code/__HELPERS/mobs.dm
  code/__HELPERS/names.dm
  code/_globalvars/lists/names.dm
  code/game/machinery/computer/security.dm
  code/game/objects/items/cardboard_cutouts.dm
  code/game/objects/items/cards_ids.dm
  code/modules/antagonists/_common/antag_spawner.dm
  code/modules/antagonists/ert/ert.dm
  code/modules/antagonists/nukeop/nukeop.dm
  code/modules/client/preferences.dm
  code/modules/language/language.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  strings/names/first.txt
  strings/names/first_female.txt
  strings/names/first_male.txt
  strings/names/last.txt
  strings/names/last_female.txt
  strings/names/last_male.txt
Labels: DO NOT MERGE, tłumaczenie

#71 Aktywacja Away Mission
  config/awaymissionconfig.txt
Labels: feature

#83 Komunikaty AI z hermaszewskiego próba numer 2
  sound/ai/attention.ogg
  sound/ai/commandreport.ogg
  sound/ai/granomalies.ogg
  sound/ai/intercept.ogg
  sound/ai/ionstorm.ogg
  sound/ai/meteors.ogg
  sound/ai/outbreak5.ogg
  sound/ai/outbreak7.ogg
  sound/ai/poweroff.ogg
  sound/ai/poweron.ogg
  sound/ai/radiation.ogg
  sound/ai/shuttlecalled.ogg
  sound/ai/shuttledock.ogg
  sound/ai/shuttlerecalled.ogg
  sound/ai/spanomalies.ogg
  sound/ai/welcome.ogg
Labels: tłumaczenie

#91 Dźwięk ogłoszenia kapitana
  sound/misc/announce.ogg
Labels: feature

#88 Tłumaczenie quirków, przedmiotów do celów anatgów, akcji
  code/datums/action.dm
  code/datums/traits/good.dm
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
  code/game/gamemodes/objective_items.dm
Labels: tłumaczenie

#97 Dźwięki związane z papierosami i napojami
  code/game/objects/items/cigs_lighters.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  sound/items/cigarette.ogg
  sound/items/cigarette_extinguish.ogg
  sound/items/lighter_light.ogg
  sound/items/pour.ogg
Labels: feature

#101 Event rework
  code/controllers/subsystem/events.dm
  code/modules/admin/verbs/debug.dm
  code/modules/spells/spell_types/rightandwrong.dm
Labels: feature

#106 minor balance do eventow
  code/controllers/subsystem/events.dm
  code/modules/events/alien_infestation.dm
Labels: PR gotowy, balans

#107 Przywrócenie plakatów/znaków na ścianach
  icons/obj/contraband.dmi
  icons/obj/decals.dmi
Labels: PR gotowy, tłumaczenie

#105 Dodanie nowych symptomów do puli.
  code/datums/diseases/advance/symptoms/anxiety.dm
  code/datums/diseases/advance/symptoms/brainrot.dm
  code/datums/diseases/advance/symptoms/magnitis.dm
Labels: PR gotowy, balans, tłumaczenie

#114 usprawnienia bota (#80)
  code/modules/client/client_procs.dm
  code/modules/shuttle/emergency.dm
Labels: PR gotowy, balans

#115 Nerf malf AI
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/gamemodes/traitor/traitor.dm
Labels: balans

#125 fix jukeboxow
  code/controllers/subsystem/jukeboxes.dm
  code/game/machinery/dance_machine.dm
Labels: bug

#127 różne zmiany
  .gitattributes
  .gitignore
  code/modules/mob/living/simple_animal/friendly/gondola.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  tools/CreditsTool/obj/Debug/CreditsTool.csproj.CoreCompileInputs.cache
  tools/CreditsTool/obj/Debug/CreditsTool.csprojAssemblyReference.cache
  tools/CreditsTool/obj/Release/CreditsTool.csproj.CoreCompileInputs.cache
  tools/CreditsTool/obj/Release/CreditsTool.csprojAssemblyReference.cache
  tools/UnstandardnessTestForDM/UnstandardnessTestForDM/obj/x86/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  tools/UnstandardnessTestForDM/UnstandardnessTestForDM/obj/x86/Debug/UnstandardnessTestForDM.csproj.CoreCompileInputs.cache
  tools/UnstandardnessTestForDM/UnstandardnessTestForDM/obj/x86/Debug/UnstandardnessTestForDM.csprojAssemblyReference.cache
  tools/UnstandardnessTestForDM/UnstandardnessTestForDM/obj/x86/Release/UnstandardnessTestForDM.csproj.CoreCompileInputs.cache
Labels: PR gotowy, balans

#136 Zmiana systemu zapisu Poly na legacy
  code/modules/mob/living/simple_animal/parrot.dm
Labels: bug

#130 kolejny fix jukeboxa
  code/controllers/subsystem/jukeboxes.dm
  code/game/machinery/dance_machine.dm
Labels: bug

#137 Naprawienie niekompatybilności z bee
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/shuttles/emergency_discoinferno.dmm
  code/__HELPERS/AStar.dm
  code/_onclick/hud/credits.dm
  code/game/machinery/computer/cloning.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
Labels: bug, priorytet, test merge

#153 Zmiany w mapach i ruinach
  _maps/RandomRuins/SpaceRuins/DJstation.dmm
  _maps/RandomRuins/SpaceRuins/abandonedteleporter.dmm
  _maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
  _maps/RandomRuins/SpaceRuins/bus.dmm
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  _maps/RandomRuins/SpaceRuins/cloning_facility.dmm
  _maps/RandomRuins/SpaceRuins/clownplanet.dmm
  _maps/RandomRuins/SpaceRuins/crashedclownship.dmm
  _maps/RandomRuins/SpaceRuins/derelict2.dmm
  _maps/RandomRuins/SpaceRuins/derelict4.dmm
  _maps/RandomRuins/SpaceRuins/derelict5.dmm
  _maps/RandomRuins/SpaceRuins/derelict6.dmm
  _maps/RandomRuins/SpaceRuins/emptyshell.dmm
  _maps/RandomRuins/SpaceRuins/gasthelizards.dmm
  _maps/RandomRuins/SpaceRuins/gondolaasteroid.dmm
  _maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
  _maps/RandomRuins/SpaceRuins/intactemptyship.dmm
  _maps/RandomRuins/SpaceRuins/mechtransport.dmm
  _maps/RandomRuins/SpaceRuins/oldAIsat.dmm
  _maps/RandomRuins/SpaceRuins/oldteleporter.dmm
  _maps/RandomRuins/SpaceRuins/onehalf.dmm
  _maps/RandomRuins/SpaceRuins/power_puzzle.dmm
  _maps/RandomRuins/SpaceRuins/scav_mining.dmm
  _maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
  _maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
  _maps/RandomRuins/SpaceRuins/vaporwave.dmm
  _maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: balans, feature

#146 sutures i regenerative meshes
  _maps/RandomRooms/10x10/sk_rdm062_roosterdome.dmm
  _maps/RandomRooms/3x3/sk_rdm051_metagamergear.dmm
  _maps/RandomRooms/5x4/sk_rdm055_metamedical.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/oldstation.dmm
  _maps/RandomRuins/SpaceRuins/scav_mining.dmm
  _maps/RandomZLevels/wildwest.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency_meta.dmm
  _maps/shuttles/emergency_raven.dmm
  _maps/shuttles/emergency_russiafightpit.dmm
  _maps/shuttles/infiltrator_advanced.dmm
  _maps/shuttles/infiltrator_basic.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/stacks/cash.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/wrap.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/paperwork/paper.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  icons/obj/stack_objects.dmi
Labels: feature, test merge

#166 Dodanie dispenserów drone shelli do stacji
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  code/game/machinery/droneDispenser.dm
  code/modules/mob/living/simple_animal/friendly/drone/inventory.dm
Labels: feature, test merge

#167 fix round time
  code/__HELPERS/time.dm
Labels: bug, test merge
