Repository aq33/tgstation, pull requests merged in 2020-07, with the labels that each got.

#185 Zmiana wyglądu apteczek, pda i health scannera na te z tg.
  icons/obj/device.dmi
  icons/obj/pda.dmi
  icons/obj/storage.dmi
Labels: feature, test merge

#164 Fix jukeboxa i creditsów, i reverb sound
  code/__DEFINES/sound.dm
  code/_onclick/hud/credits.dm
  code/controllers/subsystem/jukeboxes.dm
  code/game/sound.dm
Labels: feature, test merge

#192 Fix random maintenance
  code/game/objects/effects/spawners/roomspawner.dm
Labels: bug, test merge

#189 fix drone dispenserów
  code/game/machinery/droneDispenser.dm
Labels: bug, test merge

#190 Overhaul airlocków
  code/game/machinery/doors/airlock.dm
  sound/machines/airlock/close.ogg
  sound/machines/airlock/close_force.ogg
  sound/machines/airlock/open.ogg
  sound/machines/airlock/open_force.ogg
Labels: feature, test merge

#175 Większa szansa na jajo
  code/game/objects/effects/spawners/lootdrop.dm
Labels: DO NOT MERGE, balans, test merge

#176 Spowolnienie jetpacka
  code/game/objects/items/tanks/jetpack.dm
Labels: DO NOT MERGE, balans

#195 IPC mogą teraz być w command
  code/modules/jobs/job_types/_job.dm
Labels: balans

#194 Klient FPS domyślnie na 60
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: balans

#193 Kremówki, amarena i zupa romana.
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/vending/boozeomat.dm
  icons/obj/drinks.dmi
  icons/obj/food/piecake.dmi
Labels: feature, grafika, porting

#200 Cybersun
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  beestation.dme
  code/__DEFINES/role_preferences.dm
  code/datums/ruins/space.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
  code/modules/ruins/spaceruin_code/forgottenship.dm
  code/modules/uplink/uplink_items.dm
  config/spaceruinblacklist.txt
  icons/mob/head.dmi
  icons/mob/simple_human.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: feature, porting, test merge

#199 Dodanie nanitów do pubbystation
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: mapping, test merge

#229 Różne fixy
  _maps/RandomRooms/3x3/sk_rdm051_metagamergear.dmm
  code/__DEFINES/sound.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/jukeboxes.dm
  code/game/objects/effects/spawners/roomspawner.dm
  code/game/sound.dm
  icons/ss13_32.png
  icons/ss13_64.png
Labels: bug, dźwięk, grafika, tweak

#241 Dodanie spalaczy do kostnic
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: feature, mapping

#243 Nowy wygląd trzymanych strzelb
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/mob/inhands/weapons/64x_guns_left.dmi
  icons/mob/inhands/weapons/64x_guns_right.dmi
Labels: grafika, porting

#252 dzwięk zamykania windowsa XP przy śmierci cyborga`
  sound/voice/borg_deathsound.ogg
Labels: dźwięk

#197 Port Zmian
  code/modules/mob/living/simple_animal/friendly/gondola.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/skeleton.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: feature, porting, test merge

#261 Revert "dzwięk zamykania windowsa XP przy śmierci cyborga`"
  sound/voice/borg_deathsound.ogg
Labels: bug, dźwięk

#264 Podmiana głosu Beepskiego
  Master
  sound/voice/beepsky/creep.ogg
  sound/voice/beepsky/criminal.ogg
  sound/voice/beepsky/freeze.ogg
  sound/voice/beepsky/god.ogg
  sound/voice/beepsky/iamthelaw.ogg
  sound/voice/beepsky/insult.ogg
  sound/voice/beepsky/justice.ogg
  sound/voice/beepsky/radio.ogg
  sound/voice/beepsky/secureday.ogg
Labels: dźwięk

#256 Overhaul ślizgania się i ślizganie się po krwi.
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/misc.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/floor/misc_floor.dm
  code/game/turfs/open/floor/plating/asteroid.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/space/space.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/guardian/abilities/major/predator.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/effects/blood.dmi
  sound/effects/splash.ogg
  sound/misc/slip.ogg
Labels: dźwięk, test merge, tweak

#266 Dymki podczas pisania, usprawnienia keybindów, tweak higieny
  beestation.dme
  code/__HELPERS/global_lists.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/lists/keybindings.dm
  code/controllers/subsystem/ticker.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/emotes.dm
  code/datums/keybinding/_defines.dm
  code/datums/keybinding/emote.dm
  code/datums/keybinding/mob.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/IPC.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/status_procs.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_defines.dm
  code/modules/shuttle/emergency.dm
Labels: bug, feature, test merge, tweak

#225 Zmiana wyglądu ścian
  icons/obj/structures.dmi
  icons/turf/walls.dmi
  icons/turf/walls/reinforced_wall.dmi
  icons/turf/walls/wall.dmi
Labels: grafika, test merge

#275 Tweaki prac
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/station_engineer.dm
Labels: test merge

#304 Port protokołów replikacji nanitów
  beestation.dme
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_programs.dm
  code/modules/research/nanites/nanite_programs/protocols.dm
  code/modules/research/techweb/all_nodes.dm
Labels: feature, porting

#309 Polskie znaki prawidłowo wyświetlające się w książkach
  code/modules/library/lib_items.dm
Labels: bug, tweak

#310 Drobne ulepszenia map (nowe bronie, krematoria, naprawa centcommu, dueling pistols)
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/modules/projectiles/guns/energy/dueling.dm
Labels: bug, feature, mapping

#263 Fixy do smartcables
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: bug, mapping, test merge

#281 Dodanie monkey uprising event
  beestation.dme
  code/_globalvars/lists/poll_ignore.dm
  code/datums/diseases/transformation.dm
  code/modules/antagonists/monkey/monkey.dm
  code/modules/events/monkey_uprising.dm
  code/modules/mob/living/carbon/monkey/combat.dm
Labels: feature, test merge

#282 Balans Dynamic
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/events/abductor.dm
  code/modules/events/blob.dm
  code/modules/events/creep_awakening.dm
  code/modules/events/devil.dm
  code/modules/events/floorcluwne.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/nightmare.dm
Labels: test merge, tweak

#311 Foodcubes-komstki :D
  beestation.dme
  code/game/machinery/cubeDispenser.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/food/food.dmi
  icons/obj/machines/Foodcube.dmi
Labels: feature, grafika

#317 Dźwięk zamykania windowsa XP jako dźwięk śmierci borga
  sound/voice/borg_deathsound.ogg
Labels: dźwięk

#323 Pistolet na wodę
  code/game/objects/structures/crates_lockers/crates/wooden.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/toy.dmi
Labels: feature

#316 Taśmy policyjne
  beestation.dme
  code/__DEFINES/layers.dm
  code/_globalvars/lists/mapping.dm
  code/game/objects/items/policetape.dm
  code/modules/vending/security.dm
  icons/obj/policetape.dmi
Labels: feature, porting, test merge
