Repository aq33/tgstation, pull requests merged in 2021-07, with the labels that each got.

#1062 Tłumaczenie na język Polski.
  .gitignore
  code/__HELPERS/priority_announce.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/antagonists/official/official.dm
  code/modules/client/preferences_toggles.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/brigphys.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/deputy.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/emt.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/gimmick.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  icons/mob/screen_elite.dmi
  icons/mob/screen_gen.dmi
  icons/mob/screen_gen_old.dmi
  icons/mob/screen_midnight.dmi
  icons/mob/screen_operative.dmi
  icons/mob/screen_plasmafire.dmi
  icons/mob/screen_retro.dmi
  icons/obj/contraband.dmi
  icons/obj/decals.dmi
Labels: Grafika

#1066 zmiany QoL
  beestation.dme
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences.dm
  code/modules/client/verbs/ooc.dm
  code/modules/clothing/shoes/colour.dm
  modular_aquila/modules/VERBS/code/modify_metacoins.dm
  modular_aquila/modules/VERBS/readme.dm
Labels: Administracyjne, Feature

#1067 quick fix peleryn
  icons/mob/neck.dmi
Labels: Grafika

#1072 Krzyże
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/kitchen_spike.dm
  icons/obj/guillotine.dmi
Labels: Grafika

#1073 Cap spare trafia do sejfu oraz fix deputy
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/CorgStation/CorgStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/ticker.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  config/Sage/game_options.txt
  config/game_options.txt
  icons/mob/landmarks.dmi
Labels: Config, Grafika, Mapping

#1078 Fix Kilo i Meta
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#1079 kserokopiarki w biurach głów departamentów
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#1080 Genetyka 2.0 oraz TGUI DNA console
  _maps/RandomZLevels/research.dmm
  code/__DEFINES/DNA.dm
  code/__DEFINES/traits.dm
  code/_onclick/click.dm
  code/datums/beam.dm
  code/datums/dna.dm
  code/datums/mutations.dm
  code/datums/mutations/_combined.dm
  code/datums/mutations/actions.dm
  code/datums/mutations/body.dm
  code/datums/mutations/sight.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/dna_console.dm
  code/game/machinery/dna_scanner.dm
  code/game/objects/items/chromosome.dm
  code/game/objects/items/dna_injector.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/transform_procs.dm
  code/modules/spells/spell_types/lichdom.dm
  html/dna_discovered.gif
  html/dna_discovered.png
  html/dna_extra.gif
  html/dna_extra.png
  html/dna_undiscovered.gif
  html/dna_undiscovered.png
  icons/mob/actions/actions_spells.dmi
  icons/obj/projectiles.dmi
  tgui/packages/tgui/interfaces/DnaConsole.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Administracyjne, Grafika, Mapping, TGUI
