Repository aq33/tgstation, pull requests merged in 2021-04, with the labels that each got.

#781 powrót jukebox 2 electric boogaloo
  _maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/shuttles/emergency_discoinferno.dmm
  _maps/templates/shelter_7.dmm
  beestation.dme
  code/__DEFINES/sound.dm
  code/game/sound.dm
  modular_aquila/modules/JUKEBOX/code/dance_machine.dm
  modular_aquila/modules/JUKEBOX/code/jukeboxes.dm
  modular_aquila/modules/JUKEBOX/readme.dm
Labels: Mapping

#755 Poprawki kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping

#793 Normalne części do bs minerów
  code/game/objects/items/circuitboards/machine_circuitboards.dm
Labels: Tweak

#798 Nadzy kowboje na Baranim Ranczo
  code/modules/admin/chat_commands.dm
Labels: Administracyjne

#805 Dodaje drone dispensery do map
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Mapping

#802 Integrated circuits addon
  beestation.dme
  modular_aquila/modules/CIRCUITY/code/subtypes/manipulation.dm
  modular_aquila/modules/CIRCUITY/code/subtypes/reagents.dm
Labels: Feature, Wymaga test merge

#833 Bluespace locker
  _maps/map_files/generic/CentCom.dmm
  beestation.dme
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/parallax.dm
  code/datums/components/stationloving.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/machinery/telecomms/broadcasting.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/pinpointer.dm
  code/modules/mining/equipment/survival_pod.dm
  code/modules/shuttle/supply.dm
  modular_aquila/modules/BLUESPACE_LOCKER/icons/locker.dmi
  modular_aquila/modules/BLUESPACE_LOCKER/objects/bluespace_locker.dm
  modular_aquila/modules/BLUESPACE_LOCKER/readme.dm
  modular_aquila/modules/BLUESPACE_LOCKER/subsystem/bluespace_locker.dm
Labels: Mapping

#841 Dodaje tinyfan w engi na kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping
