Repository aq33/tgstation, pull requests merged in 2021-01, with the labels that each got.

#574 Dodaje RTG do kupienia w Cargo
  code/modules/cargo/packs.dm
  code/modules/power/rtg.dm
  icons/obj/guns/toy.dmi
Labels: Feature, Gotowe do merge

#592 Kabelki drzwi
  code/datums/wires/airlock.dm
Labels: Gotowe do merge, Tłumaczenie

#593 Kabelki automatów
  code/datums/wires/vending.dm
Labels: Gotowe do merge, Tłumaczenie

#602 Riot Rifle
  code/game/objects/structures/crates_lockers/crates/secure.dm
  code/modules/cargo/packs.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
  config/config.txt
  config/game_options.txt
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/ammo.dmi
  icons/obj/crates.dmi
  icons/obj/guns/projectile.dmi
  icons/obj/projectiles.dmi
  sound/weapons/metalwallhit.ogg
  sound/weapons/rubberhit.ogg
Labels: Feature, Gotowe do merge, Grafika, Tweak

#605 Ambience 2: Elektryczne Boogaloo (5% więcej fałd na mózgu edition)
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/area/areas.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/spaceheater.dm
  code/game/mecha/mech_fabricator.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/mining/machine_redemption.dm
  code/modules/power/generator.dm
  code/modules/power/singularity/particle_accelerator/particle_control.dm
  code/modules/power/smes.dm
  code/modules/research/machinery/_production.dm
  code/modules/security_levels/security_levels.dm
  sound/machines/electronics/computer_mid.ogg
  sound/machines/electronics/computer_mid1.ogg
  sound/machines/electronics/computer_mid2.ogg
  sound/machines/electronics/computer_mid3.ogg
  sound/machines/electronics/computer_mid4.ogg
  sound/machines/electronics/computer_mid5.ogg
  sound/machines/electronics/computer_start.ogg
  sound/machines/electronics/computer_stop.ogg
  sound/machines/electronics/lathe_idle.ogg
  sound/machines/electronics/lathe_start.ogg
  sound/machines/electronics/lathe_stop.ogg
  sound/machines/electronics/lathe_working.ogg
  sound/machines/electronics/lathe_working2.ogg
  sound/machines/electronics/lathe_working3.ogg
  sound/machines/electronics/lathe_working4.ogg
  sound/machines/electronics/transformator_mid.ogg
  sound/machines/electronics/transformator_start.ogg
  sound/machines/electronics/transformator_stop.ogg
  sound/machines/ormsmelt.ogg
  sound/machines/thermal/scrubber_mid1.ogg
  sound/machines/thermal/scrubber_mid2.ogg
  sound/machines/thermal/scrubber_start.ogg
  sound/machines/thermal/scrubber_stop.ogg
  sound/machines/thermal/thermal_mid.ogg
  sound/machines/thermal/vent_mid.ogg
  sound/machines/thermal/vent_start.ogg
  sound/machines/thermal/vent_stop.ogg
  sound/machines/wubb.ogg
  sound/misc/delta_alert.ogg
  sound/misc/red_alert.ogg
Labels: Dźwięk, Feature, Gotowe do merge

#608 Newscaster
  code/game/machinery/newscaster.dm
  icons/obj/terminals.dmi
  sound/machines/warn1.ogg
  sound/machines/warntripple.ogg
Labels: Dźwięk, Gotowe do merge, Grafika, Tweak

#588 Omegastation
  _maps/_basemap.dm
  _maps/map_files/OmegaStation/job_changes.dm
  _maps/map_files/OmegaStation/omegastation.dmm
  _maps/omegastation.json
  config/maps.txt
Labels: Gotowe do merge, Mapping, Porting

#569 Overhaul TEGa
  code/game/machinery/cell_charger.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/power/generator.dm
  icons/obj/atmospherics/components/binary_devices.dmi
  icons/obj/power.dmi
Labels: Feature, Gotowe do merge, Tweak

#611 Poprawa kilo station vol 1
  _maps/RandomEngines/kilo_singulo.dmm
  _maps/RandomEngines/kilo_stormdrive.dmm
  _maps/RandomEngines/kilo_supermatter.dmm
  _maps/RandomEngines/kilo_teg.dmm
  _maps/RandomEngines/kilo_tesla.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Gotowe do merge

#603 Overhaul górnictwa
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/closed/wall/reinf_walls.dm
  code/game/turfs/closed/walls.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/jobs/job_types/explorer.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/mine_items.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/research/designs/mining_designs.dm
  icons/mob/feet.dmi
  icons/mob/head.dmi
  icons/mob/inhands/equipment/mining_lefthand.dmi
  icons/mob/inhands/equipment/mining_righthand.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/mob/suit.dmi
  icons/obj/closet.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/guns/energy.dmi
  icons/obj/machines/mining_machines.dmi
  icons/obj/mining.dmi
  icons/obj/objects.dmi
Labels: Feature, Gotowe do merge, Grafika, Tweak

#618 Kolejne poprawki kilo
  _maps/RandomEngines/kilo_stormdrive.dmm
  _maps/RandomEngines/kilo_supermatter.dmm
  _maps/RandomEngines/kilo_teg.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Gotowe do merge, Mapping, Tweak

#615 Port ranged atmos analyzer z bee
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/device.dmi
Labels: Feature, Grafika, Porting, Zatwierdzone

#617 Palacze pamiętają swoje ulubione wyroby tytoniowe
  code/datums/traits/negative.dm
Labels: Porting, Tweak, Zatwierdzone

#621 Poprawa i nowe sprite prowizorycznego karabinka laserowego 3 electric boogaloo
  code/modules/projectiles/guns/energy/laser.dm
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/guns/energy.dmi
Labels: Grafika, Tweak, Zatwierdzone

#622 Fix shitcode drilli
  code/game/turfs/closed/wall/reinf_walls.dm
Labels: Tweak
