Repository aq33/tgstation, pull requests merged in 2021-08, with the labels that each got.

#1085 Bicz może teraz biczować
  _maps/RandomZLevels/challenge.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/Donutstation/Donutstation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/datums/components/crafting/recipes.dm
  code/game/objects/items/melee/misc.dm
  code/game/objects/items/weaponry.dm
  code/modules/admin/battle_royale.dm
  code/modules/cargo/bounties/assistant.dm
Labels: Mapping, Administracyjne

#1083 Replaye [Gotowe do test merge] (#487)
  beestation.dme
  code/__DEFINES/subsystems.dm
  code/_globalvars/logging.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/chat.dm
  code/controllers/subsystem/demo.dm
  code/controllers/subsystem/garbage.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/turfs/change_turf.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_investigate.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/create_poll.dm
  code/modules/admin/holder2.dm
  code/modules/admin/permissionedit.dm
  code/modules/admin/secrets.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_parser.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/admin/verbs/bluespacearty.dm
  code/modules/admin/verbs/borgpanel.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/fps.dm
  code/modules/admin/verbs/getlogs.dm
  code/modules/admin/verbs/map_template_loadverb.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/admin/verbs/possess.dm
  code/modules/admin/verbs/pray.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/verbs/reestablish_db_connection.dm
  code/modules/admin/verbs/spawnobjasmob.dm
  code/modules/admin/verbs/tripAI.dm
  code/modules/admin/view_variables/mass_edit_variables.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/demo/hooks.dm
  code/modules/shuttle/on_move.dm
  code/modules/tgchat/to_chat.dm
  tools/demo_condenser.js
Labels: Feature, Wymaga test merge, Administracyjne, Narzędzia

#1087 Construction bags oraz Sheet Snatcher
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/vending/engivend.dm
  icons/obj/tools.dmi
Labels: Grafika

#1088 Corg station Update
  _maps/map_files/CorgStation/CorgStation.dmm
Labels: Mapping
